name: Security Scan

on:
  push:
    branches:
      - upgrade/security-scan-and-vulns
  schedule:
    - cron: '0 14 * * *' # Daily at 8:00 AM CDT

jobs:
  security_scan:
    uses: cccteam/github-workflows/.github/workflows/golang-security-scan.yml@9bd33146fcf411a64a107e3435850761483bc64a
    with:
      execute-trivy-scan: false
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.CCC_SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      DEPENDABOT_ALERTS_TOKEN: ${{ secrets.DEPENDABOT_ALERTS_TOKEN }}
